name: evodocker-venv
channels:
  - conda-forge
#  - bioconda
  - pytorch
dependencies:
  - python=3.9
  - libgcc=7.2
  - setuptools=59.5.0
  - pip
  - openmm=7.7
  - pdbfixer
  - cudatoolkit==11.3.*
#  - pytorch-lightning==1.5.10
  - lightning=2.*
  - biopython==1.79
  - numpy==1.21
#  - pandas==2.0.1
  - PyYAML==5.4.1
  - requests
  - scipy==1.7
  - tqdm==4.62.2
  - typing-extensions
  - wandb==0.12.21
  - modelcif==0.7
  - awscli
  - ml-collections
  - aria2
  - git
#  - bioconda::hmmer==3.3.2
#  - bioconda::hhsuite==3.3.0
#  - bioconda::kalign2==2.04
#  - pytorch::pytorch=1.12.*
#  - pytorch::pytorch=2.3.0
  - pip:
      - torch --index-url https://download.pytorch.org/whl/cu118
      - deepspeed==0.12.4
      - dm-tree==0.1.6
      - git+https://github.com/NVIDIA/dllogger.git
      - git+https://github.com/Dao-AILab/flash-attention.git@5b838a8
